[package]
name = "app"
version = "0.1.0"
edition = "2018"
license = "MIT"

[dependencies]
chrono = "0.4.31"
nanoid = "0.4.0"

[dependencies.tarantool]
tarantool = "3.0"

[lib]
test = false
crate-type = ["cdylib"]
